namespace SIPADPBT{
enum Option 
{
	Yes = 1,
	No = 0  
};
runtimeclass Model : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
Model(String question, Boolean isRight, Int32 index);
Option selectedOption;		
String question;
Boolean isRight;
Int32 index;
	}
}